[project]
name = "ollama-chat-interface"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.5.1",
    "pillow>=11.2.1",
    "streamlit>=1.46.0",
]
